# Generated by Django 3.0.5 on 2020-08-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0002_auto_20200804_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='purchase_date',
            field=models.DateField(verbose_name='Дата покупки'),
        ),
    ]
